### PR TITLE
fix: YAML icon in readme

### LINKED ISSUE #2: [BUG] icon not visible in dark mode
**Describe the bug**
The YAML icon in readme is not visible when switched to dark mode.

**Expected behavior**
A suitable icon that is visible in both modes would be a good replacement.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Sookeyy-12**
## 🛠 Fixes Issue

closes #2

### CODE REVIEW

**Comment by Sookeyy-12** [comment]
also resolves issue #3 i.e. changing ```docker-compose``` commands to ```docker compose```

**Comment by Ananya2001-an** [comment]
Hey @Sookeyy-12 Thanks for solving the issue but I can only consider the YAML icon one from your end. You must raise a PR to solve a single issue at a time. This is done so that other contributors also get a chance to work on something.

Moreover always try to assign yourself for the issue by asking before raising a PR since someone else might have started working on it already and it will be a waste of your time and effort. 

Just remove the docker compose changes so that I can your merge your PR for the icon.

**Comment by Sookeyy-12** [comment]
Removed the docker compose changes.

**Review by Ananya2001-an — APPROVED** [review]
Thanks for your contribution 😊

**Pull request merged**
